# syntax=docker/dockerfile:1

FROM golang:1.21.6 AS build-stage
WORKDIR /cmd
COPY go.mod go.sum makefile ./
RUN go mod download
COPY ./cmd/*.go ./
RUN make build/docker

FROM build-stage AS test-stage
RUN make test/race

FROM gcr.io/distroless/base-debian11 AS release-stage
WORKDIR /
COPY --from=build-stage /budgy /budgy
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/budgy"]
