services:
  backend_dev:
    image: budgy:${VERSION}
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
  backend_prod:
    image: budgy:prod
    build:
      dockerfile: Dockerfile.multistage
      context: .
      target: release-stage
    volumes:
      - .:/app
